### ISSUE TITLE
off by one between rolly-scrolly and flippy-framey

### ISSUE THREAD

**Issue by ansuz** [WilliamsNY/flippy-framey#2]
[inconsistent api stuff here](https://github.com/WilliamsNY/flippy-framey/blob/gh-pages/index.html#L68)

**Comment by lukevers** [comment]
I have a feeling that link changed, @ansuz 

that link points to this:

``` css
font-size: 64px;
```

**Comment by ansuz** [comment]
the number of frames you had to specify to rollyScrolly was off by one in relation to flippyFramey. It's corrected now.
